# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["core.py"]

doc_url = "https://payoto.github.io/fantastic_octo_spork/"

git_url = "https://github.com/payoto/fantastic_octo_spork/tree/master/"

def custom_doc_links(name): return None
